CREATE TABLE FLYWAYUSER.PRODUCT(
    ID NUMBER (10,0) NOT NULL,
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(30) NOT NULL,
    PRODUCT_COST VARCHAR(30) NOT NULL,
    CONSTRAINT "PRODUCT_ID_PK" PRIMARY KEY ("PRODUCT_ID")
);